subscription Channel($id: ID, $url: String, $limit: Int, $types: [Types]) {
  channel(id: $id, url: $url) {
    action
    payload {
      ... on Channel {
        id
        by
        url
        title
        description
        tags
        members {
          id
          handle
          avatar
        }
        present
        moments(
          limit: $limit,
          types: $types
          ) {
            id
            by
            type
            content
          }
      }
    }
  }
}
